### ISSUE TITLE
Focused Frost bite does not behave properly

### ISSUE THREAD

**Issue by mikehancoski** [danj3000/ashteki#109]
If you play two copies of frost bite and activate one copy
It deals 2 damage, cost one die and exhausts both spells

It should cost one die, deal one damage and exhaust one spell

**Comment by danj3000** [comment]
damage dealt was wrong (even un-focussed), so I have corrected. 

I haven't been able to reproduce the double exhaustion.

**Comment by danj3000** [comment]
Closing this now. Happy to reopen if the exhaustion problem happens again.
