### ISSUE TITLE
butterfly monk inexaustible ability did not fire

### ISSUE THREAD

**Issue by danj3000** [danj3000/ashteki#111]
attacked with seaside raven, monk blocked, died, no trigger

[message (3).txt](https://github.com/danj3000/ashteki/files/5819399/message.3.txt)

**Comment by kleer1** [comment]
I wrote some test cases for inexhaustible triggers firing when destroyed while blocking. I haven't been able to replicate the issue.

**Comment by danj3000** [comment]
Closing as not found. Will need more detail if it happens again.
