### ISSUE TITLE
Resize preview images

### ISSUE THREAD

**Issue by danj3000** [danj3000/ashteki#17]
Cards that were in preview articles have a transparent border so appear smaller

Remove the border

**Comment by onecrayon** [comment]
As of this post, I've only converted all the Fernanda images (so through Astrea/Koji) but you can find them here at URLs like this one:

    https://cdn.ashes.live/images/cards/{lowercase-card-name}.jpg

E.g. https://cdn.ashes.live/images/cards/rins-fury.jpg

They're all 300x420 pixels without any transparency (square corners) so you can apply whatever rounded corners, shadows, etc. that you want. You're welcome to use them for this project. Rest of the cards should be online probably this weekend.

**Comment by danj3000** [comment]
Pointing at cdn.ashes.live – cards look great.
