### ISSUE TITLE
Gameplay bug: choosing order for opponent's triggered effects

### ISSUE THREAD

**Issue by onecrayon** [danj3000/ashteki#196]
My opponent had 2 Chant of Revenge in play. I used Maeoni's Command Strike to kill his Stormwind Sniper. The game prompted *me* to choose the order in which Chant of Revenge resolves (the player who controls the effect is the one who chooses the ordering).

Relevant snippet of the log:

```
Turn 7 - Skaak
Skaak uses Maeoni Viper to deal 7 damage to Stormwind Sniper
Skaak uses Silver Snake to gain 1 status token from consume
4649matt uses Chant of Revenge to place 1 status on Chant of Revenge
4649matt uses Chant of Revenge to place 1 status on Chant of Revenge
 Skaak PASSES their main action
```

**Comment by danj3000** [comment]
removed bug label as this is how l5r implementation does it - will need to change though.

**Comment by danj3000** [comment]
fixed to reflect the rules.
players are now prompted to resolve their own triggered effects, active player goes first.
