### ISSUE TITLE
Can't create a new deck

### ISSUE THREAD

**Issue by aldenbruce** [danj3000/ashteki#207]
Hello, 

Thank you for this online implementation! I am having trouble creating a deck. There should be a "new" button somewhere or a way to import cards. 

This is currently the screen I am getting: 
![ss ash](https://user-images.githubusercontent.com/28586171/107417083-75628780-6ad2-11eb-9cf0-695d1e594cb4.JPG)

I've tried loading this in a few different browsers and reloading the page as well to no avail. Can you advise? 

Thank you!
Alden

**Comment by danj3000** [comment]
Just pushed an update that should fix this. Let me know if it works for you now.

**Comment by aldenbruce** [comment]
Awesome! Thank you Dan, it is working now.
