### ISSUE TITLE
Allow login with email address

### ISSUE THREAD

**Issue by DM-miX** [danj3000/ashteki#216]
Hi 
Have tried with 2 different user accounts that I’ve registered 
It says “issue communicating with server”

Any ideas?
Mick

**Comment by danj3000** [comment]
Hi, sorry to hear that.Are they new accounts? DanOn 13 Feb 2021 00:23, DM-miX <notifications@github.com> wrote:

Hi

Have tried with 2 different user accounts that I’ve registered

It says “issue communicating with server”

Any ideas?

Mick

**Comment by danj3000** [comment]
Forgot to say - if you let me know the username(s) I can see if there's a problem and/or delete if it remains an issue

**Comment by DM-miX** [comment]
Thanks danj. Omg so I worked it out.
I was typing my email instead of username.

I had to try a few potential usernames because it’s a been a day or 2 since I signed up.

so the actual issue :) 
Can we sign in with email as option.
Or have a way of recovering our username (just for silly people like me!)

**Comment by danj3000** [comment]
Classic 😄 For a minute there I was worried I had broken the site with my last update.
Email login is a good idea though.
