### ISSUE TITLE
Choke doesn't deal 1 damage if the pheonixborn is already exhausted.

### ISSUE THREAD

**Issue by 4649matt** [danj3000/ashteki#229]
Choke: 
"Place 1 exhaustion token on a target unexhausted Phoenixborn an opponent controls."
"Deal 1 damage to that target Phoenixborn."
If the 1st ability is false (no valid target), then the 2nd ability fails to execute. Choke card is discarded with no effect.
Choke should deal 1 damage regardless.

**Comment by danj3000** [comment]
Nick confirmed, Choke needs to place the exhaustion to deal the dmg. closing.
