### ISSUE TITLE
Copycat Bug

### ISSUE THREAD

**Issue by ShuffleBusJesse** [danj3000/ashteki#234]
When you play a Copycat, when it is time to resolve the copycat effect, the opponent is getting to choose the targets and not the copycat owner/controller.

**Comment by danj3000** [comment]
Do you remember what ability you were copying? I can add that to the existing tests - so far Molten gold and water blast are covered, but are not the most complex of cases.

**Comment by ShuffleBusJesse** [comment]
Yes I copied a Transfer
