### ISSUE TITLE
Ashes.live integration

### ISSUE THREAD

**Issue by onecrayon** [danj3000/ashteki#253]
Hey @danj3000, I think the Ashes.live API is probably at a point where you can implement Ashes.live integration whenever you like. There's a couple different ways I could see this working:

1. **Mimic the TTS module:** allow people to paste in "share links" like `https://ashes.live/decks/share/435922e8-9bc8-47c2-9827-09a9f7805698/` into Ashteki. You can then harvest the UUID from the link, and fetch the deck details via GET `https://api.ashes.live/v2/decks/shared/435922e8-9bc8-47c2-9827-09a9f7805698`.
2. **Authenticate against Ashes.live:** I could implement a passwordless OAuth flow for this (would require API development, though), or you could leverage the existing email/password login (maybe a little sketchy to do this cross-site). The benefit of this is that although it would require more dev (possibly on both our parts), you could then both read and write decks to Ashes.live from Ashteki on user's behalf in real time without them needing to do the "copy a link" song and dance.

I'm open to other ideas, as well, if you have a vision for how you'd like this to work! Just let me know if you need anything from the Ashes.live side.

**Comment by danj3000** [comment]
How does the uuid change once you publish a deck? It's it used at the same end point whether private or published?

**Comment by onecrayon** [comment]
The UUID never changes, so there's two things they could enter:

* If they enter a UUID for a *standard deck* (this is the default thing you'll be seeing for any private deck at the moment), then the UUID will never change, even when they make edits to the deck. So if they imported to Ashteki, then went back to Ashes.live and changed some things, then came back to Ashteki they would need to re-import (or Ashteki would need to check for updates). Ashteki can tell if this is the case because `is_snapshot` will be `false` in the JSON response.
* If they enter a UUID for a *snapshot* (this could be either a public snapshot or a private one; but short-term they'd all be public because that's the only thing exposed on the front-end), then the UUID will never change, and the deck's contents will also never change (the only thing they can do with a snapshot is edit title/description or delete it). In this instance, `is_snapshot` will be `true` and `is_public` will be `true` or `false` depending on whether they grabbed it from a published snapshot or not.

**Comment by danj3000** [comment]
Thanks. I think option #2 (OAuth) would be amazing, but we both probably have some other stuff to get coded first 😄
