### ISSUE TITLE
Possible Bug with Law of Domination and Mounts

### ISSUE THREAD

**Issue by Thaliak** [danj3000/ashteki#339]
When a friend used Law of Dominion to have his wounded Archasaurus Mount and my Emperor Lion kill each other, the mounted unit didn't return to his hand.

**Comment by danj3000** [comment]
Thanks for your bug reports!
do you recall if the archasaurus mount was exhausted?
I notice that the dismount ability is not coded as inexhaustible (it should be) so may not trigger in that situation.
