### ISSUE TITLE
Jungle Warrior

### ISSUE THREAD

**Issue by ShuffleBusJesse** [danj3000/ashteki#383]
Hello,

I had a Jungle Warrior that was faded away. The end of round destroy did not trigger inheritance for the Jungle Warrior. Unfortunately I didn’t have a basic die to see if the Last Orders worked.

**Comment by danj3000** [comment]
Looks like I mis-coded fade away - for allies it is 'purging' _instead_ of destroying, whereas it should do one then the other.
