### ISSUE TITLE
Polarity Mage

### ISSUE THREAD

**Issue by newtaj** [danj3000/ashteki#400]
Thanks again for all the work, in general everything is running smooth,

but of course more bugs,

Polarity Mage let me click on any of my cards after I made the mistake of selecting discard alteration (I thought I could do my opponents as well but I was wrong), I did have a character with an alteration, but I just clicked on the Polarity Mage card and it threw an error, not necessarily a bad thing to happen but I thought it might be related to the second.

Law of Sight didn't discard, It said it did but didn't actually leave play and threw a similar error

Later

-taj brings Jessa Na Ni to battle
kailephelps brings Odette Diamondcrest to battle
 kailephelps has connected to the game server
 -taj has connected to the game server
-taj has chosen their first five
-taj
good luck
kailephelps has chosen their first five
ROUND 1
Prepare phase
-taj rolls 5 basic dice
kailephelps rolls 3 basic dice
 -taj rolled the most basics so will choose first player
 -taj chooses to go second
-taj has not discarded
kailephelps has not discarded
Playerturns phase
Turn 1 - kailephelps
kailephelps plays Summon Orchid Dove
Turn 1 - -taj
-taj plays Small Sacrifice
-taj plays Chant of Revenge
Turn 2 - kailephelps
kailephelps
interesting dice spread
kailephelps uses Summon Orchid Dove to put Orchid Dove into play
Turn 2 - -taj
-taj
I'm trying to figure what you going on out as well
kailephelps
lol, I just saw you have 0 conjurations
-taj plays Blood Shaman
-taj plays Undying Heart attaching it to Blood Shaman
Turn 3 - kailephelps
-taj
yeah, this one is a little funky
kailephelps plays Small Sacrifice
kailephelps meditates Meteor to gain a 
kailephelps meditates Small Sacrifice to gain a 
kailephelps meditated 2 cards/dice
Turn 3 - -taj
-taj meditates Polarity Mage to gain a 
-taj meditates Fear to gain a 
-taj meditated 2 cards/dice
-taj plays Blood Archer
Turn 4 - kailephelps
kailephelps plays Living Doll
Turn 4 - -taj
-taj meditates Blood Shaman to gain a 
-taj meditated 1 cards/dice
 -taj attacks Odette Diamondcrest with Blood Archer
kailephelps has chosen defenders
Odette Diamondcrest takes 3 damage
Turn 5 - kailephelps
kailephelps uses Small Sacrifice
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
Turn 5 - -taj
-taj uses  to move Polarity Mage from discard to hand, and receives 1 PB damage
 -taj attacks Odette Diamondcrest with Blood Shaman
kailephelps has chosen defenders
Turn 6 - kailephelps
kailephelps uses Odette Diamondcrest to deal 2 damage to Living Doll
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
Turn 6 - -taj
 -taj PASSES their main action
Turn 7 - kailephelps
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
 kailephelps attacks Blood Archer with Orchid Dove
-taj has chosen defenders
Turn 7 - -taj
 -taj PASSES their main action
Turn 8 - kailephelps
kailephelps plays Devotion attaching it to Living Doll
kailephelps uses Devotion to remove 1 exhaustion from Living Doll
 kailephelps PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
kailephelps keeps 2 dice
-taj keeps 0 dice
End of round 1
ROUND 2
Prepare phase
kailephelps has not discarded
-taj has not discarded
Playerturns phase
Turn 1 - -taj
 kailephelps mutes spectators
 kailephelps un mutes spectators
-taj plays Chained Creations to deal 2 damage to Orchid Dove
kailephelps uses Orchid Dove to make -taj discard a card from their deck
-taj discards Undying Heart from the top of their deck
Orchid Dove is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
-taj uses Blood Archer to deal 1 damage to a unit
Turn 2 - kailephelps
kailephelps plays Summon Orchid Dove
Turn 2 - -taj
-taj plays Polarity Mage
-taj uses Polarity Mage to choose between different actions
A Server error has occured processing your game state, apologies. Your game may now be in an inconsistent state, or you may be able to continue. The error has been logged.
kailephelps
interesting
kailephelps
do we need to switch to manual?
-taj
yeah, i thought I could discard your alteration
-taj
so I clicked on the mage
-taj uses Blood Archer to deal 1 damage to a unit
Turn 3 - kailephelps
kailephelps
did you want to undo?
kailephelps
the mage only can discard your own unit's alterations
-taj
I'm kinda a don't look back type of person, but thanks
kailephelps
ok
kailephelps uses Small Sacrifice
Blood Archer is destroyed
-taj uses Chant of Revenge to place 1 status on Chant of Revenge
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
Turn 3 - -taj
-taj plays Blood Chains to destroy Blood Shaman
-taj uses Blood Shaman to remove 1 damage from Jessa Na Ni
Blood Shaman is destroyed
-taj uses Undying Heart to return Blood Shaman to hand
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
-taj uses Chant of Revenge to deal 1 damage to Odette Diamondcrest
Turn 4 - kailephelps
kailephelps plays Summon Orchid Dove
Turn 4 - -taj
-taj plays Blood Shaman
Turn 5 - kailephelps
kailephelps uses Summon Orchid Dove to put Orchid Dove into play
kailephelps meditates Enchanted Violinist to gain a 
kailephelps meditates Living Doll to gain a 
kailephelps meditated 2 cards/dice
Turn 5 - -taj
-taj plays Shepherd Of Lost Souls
-taj uses Shepherd Of Lost Souls to move Blood Archer from discard to hand
Turn 6 - kailephelps
kailephelps uses Summon Orchid Dove to put Orchid Dove into play
kailephelps attaches  to Orchid Dove
Turn 6 - -taj
 -taj PASSES their main action
Turn 7 - kailephelps
 kailephelps attacks Shepherd Of Lost Souls with Orchid Dove
-taj has chosen defenders
Shepherd Of Lost Souls takes 1 damage
Shepherd Of Lost Souls is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
kailephelps plays Redirect to redirect the damage
kailephelps uses Orchid Dove to make -taj discard a card from their deck
-taj discards Blood Shaman from the top of their deck
Orchid Dove is destroyed
Turn 7 - -taj
-taj
well dang
kailephelps
I feel like Jessa's screams are just faster than this jank that I have :)
 -taj PASSES their main action
Turn 8 - kailephelps
-taj
you got me tapped now kinda though
kailephelps uses Odette Diamondcrest to deal 2 damage to Blood Shaman
Blood Shaman is destroyed
kailephelps meditates Golden Veil to gain a 
kailephelps meditates Undying Heart to gain a 
kailephelps meditates Living Doll to gain a 
kailephelps meditated 3 cards/dice
Turn 8 - -taj
-taj
not fair game, those allies are spose to be at the bottom of the deck
kailephelps
haha
 -taj attacks Orchid Dove with Polarity Mage
kailephelps has chosen defenders
Orchid Dove takes 1 damage
Orchid Dove is destroyed
Turn 9 - kailephelps
kailephelps uses  to move Living Doll from discard to hand, and receives 1 PB damage
kailephelps plays Living Doll
Turn 9 - -taj
 -taj PASSES their main action
Turn 10 - kailephelps
kailephelps attaches  to Living Doll
 kailephelps attacks Jessa Na Ni with Living Doll
Jessa Na Ni takes 1 damage
Turn 10 - -taj
 -taj PASSES their main action
Turn 11 - kailephelps
kailephelps plays Undying Heart attaching it to Living Doll
 kailephelps PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
kailephelps keeps 0 dice
-taj keeps 0 dice
End of round 2
ROUND 3
Prepare phase
kailephelps has not discarded
-taj has not discarded
Playerturns phase
Turn 1 - kailephelps
kailephelps uses Odette Diamondcrest to deal 2 damage to Living Doll
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
Turn 1 - -taj
-taj plays Blood Archer
-taj uses Blood Archer to deal 1 damage to a unit
Turn 1 - kailephelps
kailephelps plays Devotion attaching it to Living Doll
kailephelps uses Devotion to remove 1 exhaustion from Living Doll
-taj
well, biscuits
kailephelps uses Summon Orchid Dove to put Orchid Dove into play
Turn 1 - -taj
-taj meditates Fear to gain a 
-taj meditated 1 cards/dice
 -taj PASSES their main action
Turn 1 - kailephelps
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
kailephelps uses Small Sacrifice
kailephelps uses Orchid Dove to make -taj discard a card from their deck
-taj discards Polarity Mage from the top of their deck
Orchid Dove is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
Turn 1 - -taj
-taj plays Shepherd Of Lost Souls
-taj uses Shepherd Of Lost Souls to move Blood Shaman from discard to hand
Turn 1 - kailephelps
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
kailephelps uses Summon Orchid Dove to put Orchid Dove into play
Turn 1 - -taj
-taj plays Blood Shaman
Turn 1 - kailephelps
kailephelps uses Summon Orchid Dove to put Orchid Dove into play
Turn 1 - -taj
-taj plays Law of Sight
-taj uses Law of Sight
-taj draws 2 extra card
kailephelps draws 0 extra card
 -taj PASSES their main action
Turn 1 - kailephelps
kailephelps plays Blood Chains to destroy Orchid Dove
kailephelps uses Orchid Dove to make -taj discard a card from their deck
-taj discards Final Cry from the top of their deck
Orchid Dove is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
Turn 1 - -taj
 -taj PASSES their main action
Turn 1 - kailephelps
 kailephelps PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
kailephelps keeps 1 dice
-taj keeps 0 dice
-taj uses Law of Sight to discard Law of Sight
A Server error has occured processing your game state, apologies. Your game may now be in an inconsistent state, or you may be able to continue. The error has been logged.
End of round 3
ROUND 4
Prepare phase
kailephelps has discarded 1 cards from hand
-taj has not discarded
Playerturns phase
Turn 1 - -taj
-taj uses Blood Archer to deal 1 damage to a unit
-taj plays Blood Chains to destroy Blood Shaman
-taj uses Blood Shaman to remove 1 damage from Jessa Na Ni
Blood Shaman is destroyed
-taj uses Chant of Revenge to place 1 status on Chant of Revenge
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
Turn 1 - kailephelps
kailephelps uses Small Sacrifice
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
Turn 1 - -taj
-taj uses Chant of Revenge to deal 1 damage to Odette Diamondcrest
-taj plays Blood Chains to destroy Blood Archer
Blood Archer is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
Turn 1 - kailephelps
kailephelps
lol
kailephelps plays Small Sacrifice
Turn 1 - -taj
-taj
yeah, rough break there
-taj
law of sight shouldn't be in play if it messes with anything?
-taj plays Shepherd Of Lost Souls
-taj uses Shepherd Of Lost Souls to move Blood Archer from discard to hand
 Sagerhero has joined the game as a spectator
Turn 1 - kailephelps
kailephelps
was law of sight supposed to go away last round?
kailephelps uses Summon Orchid Dove to put Orchid Dove into play
-taj
yeah, don't know what happened
kailephelps
oh, we should fix that
kailephelps
I definitely was confused on my reactions...
 -taj is attempting to switch manual mode on
 kailephelps allows enabling manual mode
 -taj switches manual mode on
Turn 1 - -taj
 -taj switches manual mode off
 Sagerhero has left the game
-taj
it doesn't want to get fixed but let me know and we can go manual
-taj
I'll report the bug
kailephelps
ok, thanks!
-taj plays Blood Archer
-taj meditates Fear to gain a 
-taj meditated 1 cards/dice
Turn 1 - kailephelps
kailephelps plays Sword of Virtue to choose between different actions
kailephelps removes all exhaustion tokens from Living Doll
Turn 1 - -taj
-taj uses Blood Archer to deal 1 damage to a unit
Polarity Mage is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
 -taj is attempting to switch manual mode on
 kailephelps allows enabling manual mode
 -taj switches manual mode on
 -taj exhausts ceremonial power die
 -taj manually moves Final Cry from their hand to their discard
kailephelps
I would like to redirect the final cry
-taj
nice
kailephelps
but I guess I do that on my turn?
-taj
well, not nice, but can you exaust
 kailephelps exhausts charm power die
-taj
you would just drag it from hand to discard
 kailephelps manually moves Redirect from their hand to their discard
-taj
it's kinda akward
kailephelps
ah
 kailephelps adds a damage to Living Doll
 kailephelps adds a damage to Living Doll
kailephelps
we're good?
-taj
yeah, good move
 -taj switches manual mode off
 -taj PASSES their main action
Turn 1 - kailephelps
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
kailephelps uses Small Sacrifice
Turn 1 - -taj
 -taj PASSES their main action
Turn 1 - kailephelps
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
kailephelps uses Odette Diamondcrest to deal 2 damage to Living Doll
Turn 1 - -taj
 -taj PASSES their main action
Turn 1 - kailephelps
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
kailephelps uses Summon Orchid Dove to put Orchid Dove into play
-taj
more in reach for Odette but still a bit of a hill
Turn 1 - -taj
 -taj PASSES their main action
Turn 1 - kailephelps
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
 kailephelps attacks Blood Archer with Living Doll
-taj has chosen defenders
Turn 1 - -taj
 -taj PASSES their main action
Turn 1 - kailephelps
kailephelps attaches  to Orchid Dove
 kailephelps attacks Shepherd Of Lost Souls with Orchid Dove
-taj has chosen defenders
Shepherd Of Lost Souls takes 1 damage
Shepherd Of Lost Souls is destroyed
Turn 1 - -taj
 -taj PASSES their main action
Turn 1 - kailephelps
 kailephelps PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
-taj keeps 0 dice
kailephelps keeps 0 dice
-taj uses Law of Sight to discard Law of Sight
A Server error has occured processing your game state, apologies. Your game may now be in an inconsistent state, or you may be able to continue. The error has been logged.
End of round 4
ROUND 5
Prepare phase
-taj has not discarded
kailephelps has not discarded
Playerturns phase
Turn 1 - kailephelps
kailephelps uses Small Sacrifice
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
Turn 1 - -taj
-taj uses Small Sacrifice
Shepherd Of Lost Souls is destroyed
-taj uses Chant of Revenge to place 1 status on Chant of Revenge
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
Turn 1 - kailephelps
kailephelps
could I redirect that?
 kailephelps is attempting to switch manual mode on
 -taj allows enabling manual mode
 kailephelps switches manual mode on
 kailephelps exhausts charm power die
 kailephelps manually moves Redirect from their hand to their discard
 kailephelps removes a damage from Odette Diamondcrest
 kailephelps adds a damage to Living Doll
-taj
then clicking manual mode again brings ya back
 Sagerhero has joined the game as a spectator
 Sagerhero has left the game
 kailephelps switches manual mode off
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
kailephelps uses Small Sacrifice
kailephelps uses Orchid Dove to make -taj discard a card from their deck
-taj discards Blood Archer from the top of their deck
Orchid Dove is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
Turn 1 - -taj
-taj uses Chant of Revenge to deal 1 damage to Odette Diamondcrest
-taj plays Reclaim Soul to destroy Blood Archer
Blood Archer is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
-taj removes 2 damage tokens from Jessa Na Ni
Turn 1 - kailephelps
kailephelps uses Odette Diamondcrest to deal 2 damage to Living Doll
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
Turn 1 - -taj
-taj plays Polarity Mage
-taj uses Polarity Mage to choose between different actions
-taj plays Undying Heart attaching it to Polarity Mage
Turn 1 - kailephelps
kailephelps uses Living Doll to move 1 damage to opponent phoenixborn
 kailephelps PASSES their main action
Turn 1 - -taj
-taj meditates Undying Heart to gain a 
-taj meditated 1 cards/dice
 -taj attacks Orchid Dove with Polarity Mage
kailephelps has chosen defenders
Orchid Dove takes 1 damage
kailephelps uses Orchid Dove to make -taj discard a card from their deck
-taj discards from the top of their deck
Orchid Dove is destroyed
kailephelps
gg
-taj uses Jessa Na Ni to deal 1 damage to Odette Diamondcrest
Odette Diamondcrest is destroyed
 -taj has won the game
-taj
gg

**Comment by danj3000** [comment]
Law of sight issue resolved, so this now just to track polarity mage
