### ISSUE TITLE
Anchornaut can ace itself.

### ISSUE THREAD

**Issue by newtaj** [danj3000/ashteki#402]
Only issue in this one is that it seems like anchornaut can choose itself as a target, it's close to the last thing I did.  Hey I want to support you on patreon but I was thinking more like 2 bucks a month and I can't do choose a lower amount for no reward, just a suggestion.  

codyd1024 brings Echo Greystorm to battle
-taj brings Jessa Na Ni to battle
 codyd1024 has connected to the game server
 -taj has connected to the game server
-taj
yeah you too
codyd1024 has chosen their first five
-taj has chosen their first five
-taj draws 1 card to their maximum of 5
ROUND 1
Prepare phase
codyd1024 rolls 5 basic dice
-taj rolls 2 basic dice
 codyd1024 rolled the most basics so will choose first player
 codyd1024 chooses to go second
codyd1024 has not discarded
-taj has not discarded
Playerturns phase
Turn 1 - -taj
-taj plays Summon Frostback Bear
Turn 1 - codyd1024
codyd1024 plays Summon False Demon
Turn 2 - -taj
-taj plays Strengthen
Turn 2 - codyd1024
codyd1024 plays Summon Ghostly Mount
Turn 3 - -taj
-taj plays Living Doll
-taj plays Root Armor attaching it to Living Doll
Turn 3 - codyd1024
codyd1024 plays Resonance
codyd1024 uses Resonance to focus Summon Ghostly Mount
codyd1024 uses Resonance to ready and raise 2 dice
codyd1024 plays Raptor Herder
codyd1024 uses Raptor Herder to put Raptor Hatchling into play
Turn 4 - -taj
-taj plays Crimson Bomber
Turn 4 - codyd1024
codyd1024 uses Summon Ghostly Mount to remove Raptor Herder from the game
 codyd1024 attacks Crimson Bomber with Spectral Charger Mount
-taj uses Jessa Na Ni to guard
Jessa Na Ni takes 4 damage
Turn 5 - -taj
-taj meditates Fear to gain a 
-taj meditated 1 cards/dice
-taj uses Summon Frostback Bear to put Frostback Bear into play
Turn 5 - codyd1024
codyd1024 plays Resummon
Turn 6 - -taj
-taj uses Strengthen to apply a lasting effect to Living Doll
 -taj attacks Spectral Charger Mount with Living Doll
codyd1024 uses Echo Greystorm to guard
Echo Greystorm takes 2 damage
Turn 6 - codyd1024
codyd1024 uses Resummon to destroy Spectral Charger Mount
codyd1024 uses Spectral Charger Mount to return its ally to hand
Spectral Charger Mount is destroyed
Turn 7 - -taj
 -taj attacks Spectral Charger Mount with Frostback Bear
Frostback Bear takes 4 damage
Spectral Charger Mount takes 2 damage
Frostback Bear is destroyed
Spectral Charger Mount is destroyed
Turn 7 - codyd1024
codyd1024 meditates Chaos Gravity to gain a 
codyd1024 meditates Raptor Herder to gain a 
codyd1024 meditated 2 cards/dice
codyd1024 plays Raptor Herder
codyd1024 uses Raptor Herder to put Raptor Hatchling into play
Turn 8 - -taj
Crimson Bomber is destroyed
-taj uses Crimson Bomber to place 1 damage on Raptor Hatchling, Raptor Herder, and Living Doll
Raptor Hatchling is destroyed
Raptor Herder is destroyed
 -taj PASSES their main action
Turn 8 - codyd1024
codyd1024 uses Summon False Demon to put False Demon into play
codyd1024 uses False Demon to deal 1 damage to a target exhausted unit
Turn 9 - -taj
 -taj PASSES their main action
Turn 9 - codyd1024
 codyd1024 attacks Living Doll with False Demon
Living Doll takes 1 damage
Turn 10 - -taj
 -taj PASSES their main action
Turn 10 - codyd1024
 codyd1024 PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
codyd1024 keeps 0 dice
-taj keeps 0 dice
End of round 1
ROUND 2
Prepare phase
codyd1024 has not discarded
-taj has not discarded
Playerturns phase
Turn 1 - codyd1024
codyd1024 uses Echo Greystorm to exhausts Living Doll
 Gravity flux exhaustion token must be removed using MANUAL MODE
 codyd1024 attacks Living Doll with False Demon
codyd1024 discards Anchornaut
codyd1024 plays Crescendo to deal 1 damage to False Demon
Living Doll takes 2 damage
-taj uses Jessa Na Ni to guard
Jessa Na Ni takes 2 damage
Turn 1 - -taj
 -taj is attempting to switch manual mode on
 codyd1024 allows enabling manual mode
 -taj switches manual mode on
 -taj removes an exhaustion from Living Doll
 -taj switches manual mode off
-taj uses Living Doll to move 1 damage to opponent phoenixborn
-taj plays Anchornaut
-taj uses Anchornaut to deal 1 damage to Raptor Hatchling
Raptor Hatchling is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Echo Greystorm
Turn 2 - codyd1024
codyd1024 plays Flute Mage
codyd1024 uses Flute Mage to remove 1 exhaustion from False Demon
Turn 2 - -taj
-taj uses Living Doll to move 1 damage to opponent phoenixborn
-taj plays Frost Bite
Turn 3 - codyd1024
codyd1024 uses Summon Ghostly Mount
codyd1024
Hah! Well that's one way to learn you can't do that on a conjuration
codyd1024
lol
 -taj is attempting to switch manual mode on
 codyd1024 allows enabling manual mode
 -taj switches manual mode on
codyd1024
It's ok :)
-taj
yeah if you click your die it will give them back and you can re exaust the demon
codyd1024
My mistake
-taj
nah it's easy
 codyd1024 removes an exhaustion from Summon Ghostly Mount
 codyd1024 readies illusion class die
 codyd1024 readies sympathy class die
-taj
and click on your side action
 codyd1024 sets their side action to unspent
codyd1024
Ahhh cool
codyd1024
:)
 codyd1024 switches manual mode off
-taj
you can also move the exhaust from the mage to the demon if you want
codyd1024
no,no it's ok, too much game state has changed
codyd1024
I appreciate it though!
 -taj is attempting to switch manual mode on
 -taj is attempting to switch manual mode on
 -taj is attempting to switch manual mode on
 codyd1024 disallows enabling manual mode
 codyd1024 disallows enabling manual mode
 codyd1024 disallows enabling manual mode
codyd1024
:)
-taj
yeah cool
 codyd1024 attacks Anchornaut with False Demon
Anchornaut takes 2 damage
Anchornaut is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Echo Greystorm
Turn 3 - -taj
-taj uses Living Doll to move 1 damage to opponent phoenixborn
-taj uses Frost Bite to deal 1 damage to Echo Greystorm
Turn 4 - codyd1024
codyd1024 uses Resummon to destroy False Demon
False Demon is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Echo Greystorm
codyd1024 meditated 0 cards/dice
Turn 4 - -taj
-taj meditates Final Cry to gain a 
-taj meditates Frost Bite to gain a 
-taj meditates Fear to gain a 
-taj meditated 3 cards/dice
-taj plays Molten Gold to place 3 damage on Echo Greystorm
Turn 5 - codyd1024
codyd1024 plays Summon False Demon
Turn 5 - -taj
-taj uses  to move Crimson Bomber from discard to hand, and receives 1 PB damage
-taj plays Crimson Bomber
Turn 6 - codyd1024
 codyd1024 attacks Crimson Bomber with False Demon
False Demon takes 3 damage
Crimson Bomber takes 2 damage
False Demon is destroyed
Crimson Bomber is destroyed
Turn 6 - -taj
-taj uses Strengthen to apply a lasting effect to Living Doll
 -taj attacks Echo Greystorm with Living Doll
Echo Greystorm takes 2 damage
Turn 7 - codyd1024
codyd1024 uses Summon False Demon to put False Demon into play
Turn 7 - -taj
 -taj PASSES their main action
Turn 8 - codyd1024
 codyd1024 attacks Jessa Na Ni with False Demon
Jessa Na Ni takes 2 damage
Turn 8 - -taj
 -taj PASSES their main action
Turn 9 - codyd1024
codyd1024 uses  to draw 1 card
codyd1024 plays Shared Sorrow to discard Shared Sorrow
Turn 9 - -taj
 -taj PASSES their main action
Turn 10 - codyd1024
 codyd1024 PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
codyd1024 keeps 0 dice
-taj keeps 0 dice
End of round 2
ROUND 3
Prepare phase
codyd1024 has not discarded
-taj has not discarded
Playerturns phase
Turn 1 - -taj
-taj plays Blood Shaman
-taj meditates Blood Shaman to gain a 
-taj meditates Crimson Bomber to gain a 
-taj meditated 2 cards/dice
Turn 2 - codyd1024
codyd1024 plays River Skald
codyd1024 uses River Skald to draw 1 cards
codyd1024 discards Adrenaline Rush
codyd1024 discards Adrenaline Rush to deal 2 damage to Blood Shaman
Blood Shaman is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Echo Greystorm
codyd1024 uses Summon Ghostly Mount to remove River Skald from the game
Turn 2 - -taj
-taj uses Strengthen to apply a lasting effect to Living Doll
-taj plays Close Combat to deal 2 damage to Spectral Charger Mount
codyd1024 uses Spectral Charger Mount to return its ally to hand
Spectral Charger Mount is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Echo Greystorm
Turn 3 - codyd1024
codyd1024 plays Chaos Gravity to exhausts Living Doll
codyd1024 moves an exhaustion token from False Demon to False Demon
codyd1024 removes an exhaustion token from False Demon
codyd1024 meditates Flute Mage to gain a 
codyd1024 meditated 1 cards/dice
Turn 3 - -taj
-taj plays Blood Chains to destroy Living Doll
Living Doll is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Echo Greystorm
-taj uses  to move Anchornaut from discard to hand, and receives 1 PB damage
Turn 4 - codyd1024
codyd1024 uses Resummon to destroy False Demon
False Demon is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Echo Greystorm
Turn 4 - -taj
codyd1024
ahhh hahaha
codyd1024
gg
-taj plays Anchornaut
codyd1024
Oh wait --- you don't have a nature
codyd1024
I guess I survive a bit longer
-taj uses Anchornaut to deal 1 damage to Anchornaut
Anchornaut is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Echo Greystorm
Echo Greystorm is destroyed
 -taj has won the game
-taj
sorry I shouldn't of been able to do that
 -taj is attempting to switch manual mode on
 codyd1024 allows enabling manual mode
 -taj switches manual mode on
codyd1024
That's interesting haha
-taj
can't undo oops
codyd1024
No worries :)
codyd1024
I was pretty toast
codyd1024
anyway!
-taj
yeah I think I could of frostbited
codyd1024
I'll report it in the ashteki channel
-taj
hey I got a better way but thanks for offering, it's nice to do
-taj
I'll copy the chat and report in the github
codyd1024
Ahhh ok. Yeah, I jsut did but a github issue is probably better
codyd1024
oops
-taj
good to play with you, mounts are tough
codyd1024
Yeah --- I lost to them earlier as a similiar echo deck --- and was just like --- why don't I just use them
-taj
trust me he doesn't mind, he did all this work for us to play here anyway
codyd1024
Seems like there are a few archtypes that are pretty significantly better :/
-taj
yeah mounts are super fun
-taj
but, some of the other decks do seem stronger
-taj
everything is worth a shot though
codyd1024
Yeah definitely :)
-taj
good to play with you gg
codyd1024
Anyway, gg -- gonna go tweak a bit
 codyd1024 has left the game

**Comment by danj3000** [comment]
Thanks for letting me know about patreon. I have adjusted the patreon tiers to suit USD amounts better, but unfortunately as I am in the UK patreon does it's own currency conversion thing, adds 50 cents, and comes up with a rounded number that is still only a bit lower than before.

So I have also set up a paypal.me link (paypal.me/ashteki) for complete flexibility. 

And finally.... Fix incoming for Anchornaut.
