### ISSUE TITLE
Exhausted while attacking

### ISSUE THREAD

**Issue by kphelps-hub** [danj3000/ashteki#419]
I believe that based on the rules, if an attacking unit is exhausted, it should leave the battle and NOT get double exhausted.

Example: Night-Shade swallow dies in combat and places an exhaustion token on a fallen. The fallen became double exhausted. 

From rulebook:
Attack Resolution
During an Attack action that targets a
Phoenixborn, an attacker or blocker
may be exhausted or destroyed before
their battle begins to resolve.
• If an attacker is exhausted or
destroyed, **it leaves battle and does
not attack.**
• If a blocker is destroyed, the
attacking unit is no longer blocked
and will deal its damage to the target
Phoenixborn.
• If a blocker is exhausted, it still
blocks but cannot counter (deal
damage) and does not receive an
exhaustion token.

**Comment by danj3000** [comment]
This has been resolved, so closing now.
