### ISSUE TITLE
Regularly need to hard refresh during a game

### ISSUE THREAD

**Issue by L3xaeus** [danj3000/ashteki#462]
Hi everyone,

As the topic says, I regularly need to refresh the page with F5 to be able to interact with my opponent, or cards in game. And when I say regularly, it's sometimes at every action I do.

I'm on Chrome for the Web browser, and I play on my laptop

**Comment by danj3000** [comment]
Hi, thanks for reporting this. It doesn't sound good at all. Do you get the red 'disconnected' in the top right of the screen? What kind of ping numbers are you normally seeing - is it green or yellow?Finally, if you know your IP address that may help me check for anything logged.DanOn 17 May 2021 18:07, L3xaeus ***@***.***> wrote:
Hi everyone,
As the topic says, I regularly need to refresh the page with F5 to be able to interact with my opponent, or cards in game. And when I say regularly, it's sometimes at every action I do.
I'm on Chrome for the Web browser, and I play on my laptop

**Comment by L3xaeus** [comment]
Thanks for your feedback. It's still green like if it work, but since I can't interact at all with the card and even the chat, I need to refresh the page so I can. About the number it's around 350

For the IP adress it may be this one, I'm not sure
192.168.1.24

**Comment by danj3000** [comment]
That looks like an internal IP.If you Google 'what's my IP' in Chrome it should tell you the external oneOn 17 May 2021 20:25, L3xaeus ***@***.***> wrote:
Thanks for your feedback. It's still green like if it work, but since I can't interact at all with the card and even the chat, I need to refresh the page so I can. About the number it's around 350
For the IP adress it may be this one, I'm not sure
192.168.1.24

**Comment by danj3000** [comment]
I've deployed an update that changes the way state is handled - there are a lot of errors logged that may or may not be related to your issue. Can't say this will definitely fix it, but if you can Ctrl F5 to refresh and clear the cache and let me know how it goes...

**Comment by L3xaeus** [comment]
Excuse me for the delay. Here's my IP adress if it can help
2a01:cb22:15c:ef00:8868:a77:10f3:4f08

**Comment by L3xaeus** [comment]
I'll give it a try during FFF if I'm able to attend, I'd love to even if it's 5am for me haha

**Comment by danj3000** [comment]
Fixed!
