### ISSUE TITLE
Manual purge

### ISSUE THREAD

**Issue by danj3000** [danj3000/ashteki#568]
hey @dijon just letting u know i ran into an issue tonight and not sure if u can fix it i played a reaper angel and again it didn't let me remove an ally if i didn't do the first part which u should be able to do went into manual mode and did the command to manual remove a card from the game and i tried clicking on an ally and it wouldn't let me remove it from the game for some reason and couldn't figure it out thanks for the help

**Comment by 5H4Z** [comment]
The initial fix of Reaper Angel functionality is complete. Remaining item here is being able to purge a specific card in manual mode

**Comment by danj3000** [comment]
drag drop bf to purge, and /purge commands work, so closing
