### ISSUE TITLE
Jessa's screams of the departed isn't right

### ISSUE THREAD

**Issue by danj3000** [danj3000/ashteki#58]
got offered twice, once with double card display
couldn't pass

**Comment by mikehancoski** [comment]
Now it does not activate on opponents turn and can be activated on your turn even if nothing has been destroyed

**Comment by danj3000** [comment]
Hi Mike, 
options when I spotted the reaction problem were:
1. remove completely, and tell people to use manual mode (which I haven't tested much)
2. convert to an actions to enable use in players own turn
3. leave with multiple reaction prompts

I may have chosen poorly at the time :-)

**Comment by danj3000** [comment]
Fixed now - needed a framework tweak.
Odd images sometimes is separate issue
