### ISSUE TITLE
summon mist spirt will not allow you to summon mist spirt when you have power illusion no class illusion

### ISSUE THREAD

**Issue by mikehancoski** [danj3000/ashteki#60]
you must have a class die to use it other wise it does not light up or allow you to select it.

**Comment by danj3000** [comment]
Not sure this is 100% resolved, but summon did have the wrong cost. Fixed with test for basic summon.

**Comment by danj3000** [comment]
closing in the hope that this is sorted now - feel free to reopen if it's a problem again
