### ISSUE TITLE
Inheritance should be able to target opposing units

### ISSUE THREAD

**Issue by 5H4Z** [danj3000/ashteki#600]
From the Gilder card text, you should have the option to put status tokens on your opponent's units. While in most situations this would not be desirable, a player could be planning to use String Mage or some other effects to later take advantage of the opposing player's status tokens. From testing, Inheritance fails to trigger when the Gilder's controller has no other units, and when it triggers while the Gilder's controller has units, they cannot target units controlled by the opposing player.

**Comment by 5H4Z** [comment]
Confirmed that this is the same for Jungle Warrior, so it is common across the implementation of Inheritance

**Comment by 5H4Z** [comment]
Ditto for Brilliant Thorn

**Comment by danj3000** [comment]
Agreed - can see that the target spec in card.js is wrong

**Comment by 5H4Z** [comment]
I believe this was fixed in pull request #603
