### ISSUE TITLE
Cards taken from discard should be announced

### ISSUE THREAD

**Issue by danj3000** [danj3000/ashteki#606]
check all card selections where location: 'discard'
Could update MoveCardAction and announce if from discard / public location

doktarr:
Another thing I would like is for the text to announce what card was pulled out of discard by Polarity Mage/Shepherd/etc. It's open information so it should appear on the side.

**Comment by 5H4Z** [comment]
I conducted some testing and confirmed that the following cards announce which card was retrieved from discard:
Reaping Angel, Ceremonial power die, Soul Shepherd, Encore.
The following card did not announce which card was retrieved from discard:
Polarity Mage ('player uses Polarity Mage to choose between different actions' only),
Shared Sorrow ('player plays Shared Sorrow to discard Battle Seer' only)

**Comment by 5H4Z** [comment]
Fixed Polarity Mage as part of PR #668 
Shared Sorrow is still outstanding

**Comment by 5H4Z** [comment]
Shared Sorrow is now fixed as part of PR #668

**Comment by 5H4Z** [comment]
I think this ticket should now be closed, unless there are other examples where this is not working.

**Comment by danj3000** [comment]
agree, we can raise new issues if needed
