### ISSUE TITLE
Optional effects should be consistently coded

### ISSUE THREAD

**Issue by 5H4Z** [danj3000/ashteki#643]
- [x] Summon Timehopper Focus 1 should be optional (message for this Focus 1 prompt could be clearer too, it just asks to choose a card, which then has a status token added) - DAN
- [x] Small Sacrifice should be optional to damage the opponent's unit, however the Focus 1 wording sounds like it is optional but requires both units to become exhausted
- [x] Flock Shepherd's Gather 2 should be optional (perhaps you don't want to kill all the attacking units that you block)
- [x] Mass Heal second ability should be optional (perhaps you want to keep Blood Puppets alive)
- [x] Group Tactics should be optional (perhaps only matters if you don't want opposing units to die in combat, or impact on the quantity of a Redirect) - DAN
- [x] Ambush ability should be optional (perhaps only affects a possible Redirect or Sympathy Pain?)

- Master Vampire, Omen Bringer, Open Memories, Summon Dread Wraith focus 2, Summon Ice Golem focus 2 all say "may" but I can't think of any use cases for making these optional, so I suggest they stay as is.

**Comment by danj3000** [comment]
I agree that similar effects should be coded consistently - makes for a better user experience.
However I'm just flagging that 'may' is used in 2 contexts:
1 - where you 99% want to do it (e.g. anchornaut) and the optional: target trigger is sufficient
2 - where the action is less automatic, and the 'do you want to xyz' prompt is more appropriate

the click saving for #1 is worth the different treatment, and the question in #2 is worth it to explain what the system wants to do.

So for some cards it's likely to be subjective.

**Comment by danj3000** [comment]
all done now
