### ISSUE TITLE
Attack button does not consider Rooted ability

### ISSUE THREAD

**Issue by 5H4Z** [danj3000/ashteki#644]
Attack button should not be selectable when the only unexhausted units I have are Rooted (cannot attack), e.g. Turtle Guard or Biter. I was able to select it when I only had unexhausted Turtle Guards in play.

**Comment by 5H4Z** [comment]
Devotion also creates this ability. Perhaps this needs a named ability to be defined for these cards that the Attack button can check.

**Comment by danj3000** [comment]
This should be a small fix in actionWindow - line 75 should be c.canAttack() not !c.exhausted().
Works ok testing manually, but I'm looking into why I can't test for it - something to do with the setup of the test game.
