### ISSUE TITLE
RULES ISSUE: Undying heart on a blood shaman with fade away - the undying did not trigger

### ISSUE THREAD

**Issue by danj3000** [danj3000/ashteki#98]
Undying heart on a blood shaman with fade away - the undying did not trigger, but I think this is also a rules grey area for Skaak to confirm the resolution order. :-)

**Comment by danj3000** [comment]
both proc at the end of round, and both change the destination of the destroyed unit.

**Comment by Melkor118** [comment]
Hello,

This also occurs with Undying Heart on Blood Archer when being destroyed by Fear

**Comment by danj3000** [comment]
RE: Undying Heart on Blood Archer when being destroyed by Fear
Has been fixed in a different GH issue.

Remaining issue requires rules clarification therefore not likely to make change any time soon
